### ISSUE TITLE
change wording of "whitelist" to "share" consistently throughout UI

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-server#109]
To match the chrome extension https://github.com/haystack/eyebrowse-chrome-ext/commit/7a8428a693ad4974220f39bcd9fd493a24ceca52

**Comment by joshblum** [comment]
also when installing many users asked what 'whitelisting' was. having the button say 'share this domain' will be more clear

**Comment by joshblum** [comment]
@karger @amyxzhang would 'sharelist' be better wording for this?

**Comment by karger** [comment]
i don't know how good it is in absolute terms but it's definitely better.
