### ISSUE TITLE
Extension asynchronous calls only/remove unnecessary info

### ISSUE THREAD

**Issue by amyxzhang** [haystack/eyebrowse-server#142]
extension is laggy.

**Comment by amyxzhang** [comment]
will be ripping out the stats for now. and converting anything sync to async

**Comment by amyxzhang** [comment]
decided to leave stats in but convert times to avg time per visit instead of total time (more useful/interesting). everything has been converted to sync. changes should be reflected in extension in a few hours.

**Comment by karger** [comment]
the conversion does lose some info; perhaps worth also reporting number
of visits (so total time can be reconstructed)

**Comment by amyxzhang** [comment]
Yes we are reporting that already.

On Wednesday, February 3, 2016, David Karger <notifications@github.com>
wrote:

> the conversion does lose some info; perhaps worth also reporting number
> of visits (so total time can be reconstructed)
>
> On 2/3/2016 11:54 AM, Amy Zhang wrote:
> >
> > decided to leave stats in but convert times to avg time per visit
> > instead of total time (more useful/interesting). everything has been
> > converted to sync. changes should be reflected in extension in a few
> > hours.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/haystack/eyebrowse-server/issues/142#issuecomment-179343240
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/eyebrowse-server/issues/142#issuecomment-179391710>
> .
>


-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh
