### ISSUE TITLE
Hide visited domains

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-server#145]
@karger idea. Add an option to hide domains you've already visited in the feed.

**Comment by amyxzhang** [comment]
Think it should be hide web*pages* you've been to and not domains.

**Comment by karger** [comment]
agreed

**Comment by joshblum** [comment]
whoops yes you're right

**Comment by amyxzhang** [comment]
Done!

**Comment by karger** [comment]
do you hide the whole domain or only the visited pages?

**Comment by amyxzhang** [comment]
only visited pages!

On Wed, Feb 24, 2016 at 3:27 PM, David Karger <notifications@github.com>
wrote:

> do you hide the whole domain or only the visited pages?
>
> On 02/24/2016 03:22 PM, Amy Zhang wrote:
> >
> > Closed #145 <https://github.com/haystack/eyebrowse-server/issues/145>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/haystack/eyebrowse-server/issues/145#event-564287039
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/eyebrowse-server/issues/145#issuecomment-188440831>
> .
>



-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh

**Comment by karger** [comment]
good that sounds right.  although for discovery it might also be nice to 
have an option for seeing popular *domains* I haven't been to before 
(and popular pages in those domains)

**Comment by karger** [comment]
should the show/hide state be sticky as I move between views?  With 
sensible exceptions, e.g. hide visited shouldn't apply when I view my 
own activity :)

**Comment by amyxzhang** [comment]
The button is not sticky right now. And it doesn't appear at all when
viewing profile pages at the moment (yours or anyone else's).

On Wed, Feb 24, 2016 at 3:45 PM, David Karger <notifications@github.com>
wrote:

> should the show/hide state be sticky as I move between views? With
> sensible exceptions, e.g. hide visited shouldn't apply when I view my
> own activity :)
>
> On 02/24/2016 03:35 PM, Amy Zhang wrote:
> > only visited pages!
> >
> > On Wed, Feb 24, 2016 at 3:27 PM, David Karger <notifications@github.com>
> > wrote:
> >
> > > do you hide the whole domain or only the visited pages?
> > >
> > > On 02/24/2016 03:22 PM, Amy Zhang wrote:
> > > >
> > > > Closed #145 <https://github.com/haystack/eyebrowse-server/issues/145
> >.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > >
> > <https://github.com/haystack/eyebrowse-server/issues/145#event-564287039
> > > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/haystack/eyebrowse-server/issues/145#issuecomment-188440831
> >
> > > .
> > >
> >
> >
> >
> > --
> > Amy X. Zhang | Ph.D. student at MIT CSAIL |
> > http://people.csail.mit.edu/axz
> > | @amyxzh
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/haystack/eyebrowse-server/issues/145#issuecomment-188444578
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/eyebrowse-server/issues/145#issuecomment-188447513>
> .
>



-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh
