### ISSUE TITLE
Request For MIT Certificate For Favicon

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-server#43]
When you are browsing the history a request for an MIT certificate appears, presumably when a webpage behind MIT certificates is requested. We should figure out a way to fail silently and not prompt the user for the cert

**Comment by karger** [comment]
one solution could be to convert all https requests to http.  Some urls 
might not resolve---perhaps this is an indication that they shouldn't?

**Comment by joshblum** [comment]
This seems very reasonable -- if the request fails and we miss a favicon its not the end of the world either. I don't think there is an simple way to check if the domain uses a cert otherwise without making a request and having it fail. Seems too complicated and the simple solution is much better

**Comment by amyxzhang** [comment]
Hm I don't think this fixed the problem for me - open in incognito: http://eyebrowse.csail.mit.edu/users/dionlow

**Comment by joshblum** [comment]
Ah the `add_favicon` command only updates `EyeHistory` objects that don't have a favicon. I manually called `save()` on the objects with `https` in the `favIconUrl` so it should be good now.

**Comment by amyxzhang** [comment]
Is it just me then? I still get a request for certificate if I try to open this in incognito: http://eyebrowse.csail.mit.edu/users/dionlow

**Comment by joshblum** [comment]
No I see this too for some reason I wasn't getting a prompt after the update..

`http://lms.mitx.mit.edu/static/themes/mitx/images/favicon.233eba7fdd61.ico` redirects itself to `https://` and requests the certificate. Gonna dig a bit and see what we can do.

**Comment by joshblum** [comment]
Hmm so here are a few options I can think of:

1 We store the favicons, grabbing the content while the user is authenticated and then storing it. Presumably we need to periodically check for updates to the favicons..

2. Another way would be to try to request the favicons serverside beforehand and have a flag if the request fails for some reason. 

Thoughts? Any alternate suggestions?

**Comment by amyxzhang** [comment]
perhaps storing the favicons? i have noticed while staring at the network tab and loading eyebrowse pages that grabbing favicons often takes the most amount of time (few hundred ms in worst cases) of anything on the page.

**Comment by joshblum** [comment]
Cool yeah I've noticed that as well. Hopefully this can help page load times.
