### ISSUE TITLE
Database Encoding

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-server#45]
I've seen this error a few times:

```
DatabaseError: (1267, “Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='”)
```

Following [this post](http://stackoverflow.com/questions/1073295/django-character-set-with-mysql-weirdness) do you guys think the best option is to alter the DB tables? 

Just wanted to open this for discussion :)

**Comment by amyxzhang** [comment]
I thought I did this for several columns already. I will check.

**Comment by joshblum** [comment]
Is this still an issue?

**Comment by joshblum** [comment]
Going to close this for now.
