### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by amyxzhang** [haystack/eyebrowse-server#52]
We need homegrown analytics because Google Analytics just isn't really cutting it.

Ideally I would want to store:
 - visits to every page on the Eyebrowse website, including timestamp and user (if logged in), ip otherwise
 - track clicks on any link that leaves Eyebrowse, including the page that the user was on, the user (if logged in) and ip otherwise, and timestamp
 - if someone is using the visualization widgets - so I would want to track the viz API calls too, including timestamp and ip address, and in this case referrer.
 - how often do people delete things? what do people choose to delete?

Also what about extension analytics?
- How often do people turn Eyebrowse on and off? Do they even use this feature?

Anything else?

Don't forget to still have the links open in a new window on click.
Be careful not to log pings
Need to rip out old Google Analytics code

**Comment by joshblum** [comment]
I think this project might be a good fit:

http://chronology.github.io/

You can basically track whatever you want on the frontend and it has some nice viz components as well.

**Comment by joshblum** [comment]
@karger @amyxzhang Does this project fit what we're looking for in terms of tracking? Can we have a separate openstack instance for this?

**Comment by amyxzhang** [comment]
we could set up a small machine (other people are hogging the RAM on our OpenStack acct). tbh it's a bit more heavy/prod than I was envisioning - I mean, there's no need for a real-time analytics engine or a separate db optimized for logging (is there a need?), but if it's pretty standalone/plug-and-play then maybe that's fine. and if you're comfortable with it then that's good too.

**Comment by joshblum** [comment]
Hmm it might be a bit much. I've used it end to end but have contributed and know that is very flexible. My worry is that hand rolling will turn into a headache in the end and it will be hard to make any ad hoc queries if we want. Another option is using segment: https://segment.com/docs/libraries/analytics.js/

**Comment by joshblum** [comment]
I'd like to go ahead with the chronology project. If it seems like too much/too complicated I'll setup segment (i think the free option is fine and that they have some viz) or start handrolling. The nice thing about chronology is that we can log stuff in the extensions too, especially errors to help bug track. Let's chat about the openstack stuff?

**Comment by amyxzhang** [comment]
ok. I can set up a small instance for you on openstack and give you key access. I'll still be able to log in via my CSAIL.

**Comment by amyxzhang** [comment]
I've added some simple analytics - basically just tracking which pages users visit on the eyebrowse website, when they open the eye icon to get more info on a page, and when they click on a link in any of the the livefeeds. Going to close this issue for now - if we want anything fancier we can open a new ticket.

**Comment by joshblum** [comment]
+5 :)
