### ISSUE TITLE
Notifications that actually work

### ISSUE THREAD

**Issue by amyxzhang** [haystack/eyebrowse-server#56]
notifications don't work right now really.

I'm imagining 
- a new database table to store notifications, timestamp, and when they've been seen. Can store heterogeneous notifications (new follower, bump into someone, someone tags you in a comment)
- A flag in the corner of Notifications in the nav bar with a number when you have a notification. clicking takes you to a page with a list of your last ~15 notifications.
- you get an email for every notification by default (right now you get an email only when someone follows you). Ability to turn this off partially in settings.
- notifications include - when someone follows you. when you "bump" into someone on the same *page* (they join page within 5 minutes of you joining). when someone tags you in a comment or chat. when someone comments or chats on a page that you have been to in the past.

**Comment by joshblum** [comment]
https://github.com/pinax/pinax-notifications seems like the most popular library

**Comment by amyxzhang** [comment]
thanks going to use that now

**Comment by amyxzhang** [comment]
yay notifications work! Right now you can only get notified about a new follower. you can also manage whether you want to get emails and for what.

**Comment by amyxzhang** [comment]
just unfollowed and refollowed you @karger and @joshblum so you can see the changes.

**Comment by joshblum** [comment]
:dancer: :dancer:  whoo! my only nit is the styling of the emails, we should add some newlines in there (and also do #70 eventually)

![screen shot 2015-03-22 at 11 57 47 pm](https://cloud.githubusercontent.com/assets/1144020/6771717/96f9186a-d0ef-11e4-8972-f81fcaee483d.png)

**Comment by amyxzhang** [comment]
added more spaces.

It's a bit difficult to test but I've added notifications for when bumping into a follower (being within 5 min of each other) on the same site as well. This notification has emails by default OFF.

Now adding notifications for when someone leaves a comment or message after you've been to a page.

**Comment by amyxzhang** [comment]
alright closing this now. added notifications for messages and chats and bumping. will now work on allowing tagging a person in chat or message with @ before implementing notifications of that.

to add a notification type, take a look at https://github.com/haystack/eyebrowse-server/blob/master/scripts/install_notification_types.py#L11
the default value sets whether you want it to be emailed by default or no (2=yes, 0=no)

then pass either send_now() or queue() when creating the notification (created by making a Notification obj).
