### ISSUE TITLE
sync twitter to find friends

### ISSUE THREAD

**Issue by amyxzhang** [haystack/eyebrowse-server#64]
sync is written but not friend suggestion. add to getting started too.

**Comment by joshblum** [comment]
Are there any other social services that might be good? Facebook? Github? Stackoverflow?

**Comment by amyxzhang** [comment]
I was thinking fb but that's it

On Saturday, March 14, 2015, Joshua Blum <notifications@github.com> wrote:

> Are there any other social services that might be good? Facebook? Github?
> Stackoverflow?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/eyebrowse-server/issues/64#issuecomment-80407023>
> .
>


-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh

**Comment by joshblum** [comment]
Github may be nice since that's once of the main things I share.. Not high
priority not sure how easy it is to setup auth extra

**Comment by amyxzhang** [comment]
It's pretty easy to setup auths. Hm if you think we can get some traction among the github/coding/SO community to use Eyebrowse, that would be a really cool use case to study!

**Comment by joshblum** [comment]
I think it would be a good area to target since from the people i've talked to the things they are most willing to share are SO/github and news articles

**Comment by amyxzhang** [comment]
Twitter friend syncing is done.

**Comment by amyxzhang** [comment]
I'm going to close this for now and open issues for other accts to sync as we find the desire/need for them.
