### ISSUE TITLE
Resize base64 encoded images

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-server#66]
After fixing the favicons the bas64 images are stretched when displayed in my activity. Need some javascript for resizing:
http://stackoverflow.com/questions/20958078/resize-base64-image-in-javascript-without-using-canvas

**Comment by joshblum** [comment]
Seems like the resizing isn't a problem with base64 but just that favicons are too small. 31dc518b0b848a6e906b2c5eda0b8f9b927542a1 closes this

**Comment by amyxzhang** [comment]
I wanted to mention that I see a lot of blank squares for the following and firehose view (the ones that use the PopularHistoryInfo model instead of EyeHistory)

**Comment by joshblum** [comment]
I think this is fixed with 896424b there were some old refs to `favIconUrl`
