### ISSUE TITLE
Frontend Facelift

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-server#67]
I'm a bit tired of the grey on grey (nav/background) and think the site would look a lot cleaner by making it white/something brighter. I think github style is a good example that we can maybe follow

**Comment by amyxzhang** [comment]
yes!!!! +++++1

On Sat, Mar 14, 2015 at 6:58 PM, Joshua Blum <notifications@github.com>
wrote:

> I'm a bit tired of the grey on grey (nav/background) and think the site
> would look a lot cleaner by making it white/something brighter. I think
> github style is a good example that we can maybe follow
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/eyebrowse-server/issues/67>.
>



-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh
