### ISSUE TITLE
Bug with viz

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-server#68]
Syntax error from js reformatting when trying to view visualizations on profile page

**Comment by amyxzhang** [comment]
i pushed one fix to a bug related to viz but that one doesn't resolve the syntax error.

**Comment by joshblum** [comment]
yeah this is my fault from something with the js changes i'll take a look
in a bit

**Comment by joshblum** [comment]
9b440d8a122d48945fcbd874c120df8ffc787f5d closes this
