### ISSUE TITLE
Incorporate Mobile Data

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-server#82]
Should involve a bit of extension hacking to access the history and push it to the server. Some things to keep in mind compliments of @karger 

1) history doesn't tell you how long someone spent on a page (and doesn't catch tab switches)
2) this will mean browsing events arrive very out of order, which may have ramifications for how we store/query the stream (but indexing the db on visit time may make this transparent/irrelevant)
3) if you do this on every device, it will be important to detect/ignore duplicate history events being transmitted from multiple devices.

The checking should also be done fairly frequently so we should have some type of diff checking and, if possible attribution to where the item originated (which device the history was accessed on)

**Comment by amyxzhang** [comment]
I tried today to see if I could access any mobile history from the extension api locally and I couldn't. :( At least just using https://developer.chrome.com/extensions/history and querying for things in my recent mobile history turned up nothing.

**Comment by joshblum** [comment]
yeah same :/


lets see if anything turns up here: http://stackoverflow.com/questions/29445043/access-chrome-mobile-sync-history

if not we'll close
