### ISSUE TITLE
Investigate using chrome notifications for whitelisting/login prompts

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-server#86]
https://support.google.com/chrome/answer/3220216?hl=en

**Comment by joshblum** [comment]
It seems that the notifications appear in the system tray which we don't really want(https://developer.chrome.com/apps/notifications) , so I would say we leave the prompts as they are. @amyxzhang @karger sound ok?

**Comment by amyxzhang** [comment]
Yeah, I'm happy with the prompts the way they are actually.
