### ISSUE TITLE
Populate top feed for new users

### ISSUE THREAD

**Issue by amirw** [haystack/eyebrowse-server#89]
Upon registration and following of Mr. @joshblum, All feeds except "most recent" were empty.
I would expect a non empty field to be the default.

**Comment by amyxzhang** [comment]
sorry, you need to run the script populate_popular_history.py in scripts/cron_tasks:

from scripts.cron_tasks.populate_popular_history import *
populate_popular_history()

This is a cron task that runs once every 6 hours and updates the popular feeds. I will add to the startup docs.

**Comment by amyxzhang** [comment]
added to docs: 4890d2feda1f2a499e4deba5f874e32cf693a989

**Comment by karger** [comment]
why run only once every 6 hours?

**Comment by joshblum** [comment]
I think this is referring to the user experience upon signup, not just for devs. also I think we should change 4890d2f to include `python manage.py installtasks` in the makefile rather than another ad hoc command

**Comment by amyxzhang** [comment]
I think it's actually set right now at once an hour but I've noticed that the site gets noticeably slower when it's running (so I've asked to perhaps move it to less often). We need a larger machine or a dedicated machine but haystack's openstack account is close to full. Can we request more memory and cores @karger?

**Comment by karger** [comment]
it's surprising that with only 10 users eyebrowse is loading any machine 
at all.  We should find out what the performance issues are since they 
will hound us as the userbase grows---even if we can upgrade machine 
now, that won't help us when we have more users. It's often just a 
matter of creating an index on a relevant column of a table.

**Comment by joshblum** [comment]
we're going to kick off an update when users follow/unfollow others. Need this to run asynchronously, looking into celery and @amyxzhang is going to modify the algorithm to work on a per user basis
https://realpython.com/blog/python/asynchronous-tasks-with-django-and-celery/

**Comment by amyxzhang** [comment]
Ok added to code to *synchronously* update popular history feed when following/unfollowing others. It's a little slow (~10-15 seconds) to run, so I added a loading gif to the button. I think it could be made faster too, not sure. Closing this for now.
