### ISSUE TITLE
Trouble installing extension

### ISSUE THREAD

**Issue by JCSchiavone** [haystack/eyebrowse-server#93]
When installing, get following error: UTILITY_PROCESS_CRASHED_WHILE_TRYING_TO_INSTALL. Advised to restart Chrome and try again, but that doesn't help.

Using Chrome 40.0.2214.111 (64-bit) on Ubuntu 14.04

**Comment by joshblum** [comment]
Hey @JCSchiavone sorry that you're having issues. I found the following which may be helpful:

https://code.google.com/p/chromium/issues/detail?id=401655
http://graysonpeddie.com/utility-process-crashed-while-trying-to-install-in-google-chrome/
http://graysonpeddie.com/utility-process-crashed-while-trying-to-install-in-google-chrome/

I don't have an ubuntu machine to test on (sorry!) but let me know if this helps.

**Comment by joshblum** [comment]
@JCSchiavone are you still having a problem or can we close the issue?

**Comment by joshblum** [comment]
Closing this for now, we can reopen if necessary
